### ISSUE TITLE
[Bug]: Performance issue on android for existing app 

### ISSUE THREAD

**Issue by santoshgistto** [hm21/pro_image_editor#115]
### Package Version

4.0.0

### Flutter Version

3.22.2

### Platforms

Android

### How to reproduce?

Integrate flutter in existing app 
Ref : https://docs.flutter.dev/add-to-app/android/project-setup?tab=without-android-studio
launch the flutter screen with editor 

https://github.com/hm21/pro_image_editor/assets/12577046/22b93494-7654-4c4c-9e20-6d08497d2c42

**Comment by hm21** [comment]
I have a few more questions:

1. On which device you test it? As example Samsung Galaxy S22. 
2. Do you test it with the emulator or a real device? 
3. Do you create a release build or is this in the debug mode?
4. You think there is a performance impact over all or mostly on the emoji-editor?

**Comment by santoshgistto** [comment]
On which device you test it? As example Samsung Galaxy S22. - > Galaxy A15
Do you test it with the emulator or a real device? - real device
Do you create a release build or is this in the debug mode? - no debug build 
You think there is a performance impact over all or mostly on the emoji-editor? - over all 

Tested with release build looks much more better then debug build  
https://github.com/hm21/pro_image_editor/assets/12577046/6dd909fe-e751-4d71-8d9a-1f69f726e023

**Comment by hm21** [comment]
In your second video, where it's in the release build, I don't see any performance impact. Keep in mind that performance impact in debug mode is quite normal. But now I have more questions.

How do you configure the generation configs from the image editor, or didn't you configure anything?
```dart
configs: ProImageEditorConfigs(
  imageGenerationConfigs: const ImageGeneratioConfigs(
    generateImageInBackground: true,
    processorConfigs: ProcessorConfigs(
      processorMode: ProcessorMode.auto,
      numberOfBackgroundProcessors: 2,
      maxConcurrency: 1,
    ),
  ),
```

Can you use in Android Studio the CPU and memory profiler that we got more details?

**Comment by santoshgistto** [comment]
Default configuration 

> ProImageEditor.network('https://picsum.photos/id/237/2000',
        callbacks: ProImageEditorCallbacks(
          onImageEditingComplete: (Uint8List bytes) async {
            Navigator.pop(context);
          },
        ));

CPU and memory profiler will share in sometime

**Comment by santoshgistto** [comment]
Here is the logs https://drive.google.com/drive/folders/1SM3bLDdru2AztczNruqegutC7TWlM7fR?usp=sharing
i see some memory leaks in flutter activity mostly not related to this

**Comment by hm21** [comment]
Thanks for the logs. I just checked it but didn't see anything that looked like the problem is from the image editor. 

In the CPU, everything appears to be normal, I also see that the image editor setup all isolates that work in the background and never was all overloaded.

In the memory analysis I see that there are two leaks and when we check the file a bit we see that most things consume flutter native stuff like keyboard manager, input manager and other flutter stuff.  

The only thing I think you can try now is to disable the background generation and limit the state history to a smaller amount, maybe that will help a bit. Below I post an example of how to do it. The performance in the editor itself is already very optimized because I work a lot with streams and global keys. This is important that I not always call `setState` which rebuild everything. I also make sure that “repaint” doesn't affect other elements that don't really need to be repainted, so I don't think there is anything else I can do that will improve the performance of the editor itself.
```dart
configs: const ProImageEditorConfigs(
        stateHistoryConfigs: StateHistoryConfigs(
          stateHistoryLimit: 20,
        ),
        imageGenerationConfigs: ImageGeneratioConfigs(
          generateImageInBackground: false,
        ),
),
```
