### ISSUE TITLE
[Feature request] Max scale to Emoji's/Stickers

### ISSUE THREAD

**Issue by efalco777** [hm21/pro_image_editor#122]
### Platforms

Android, iOS

### Description

Add max scale to: **StickerEditorConfigs** & **EmojiEditorConfigs**.

### Why

Would be nice to be able pass an argument to set the max scales for both of those layers. That way we could eliminate scenarios where the set layer is scaled so much it becomes blurry or pixelated.

**Comment by efalco777** [comment]
Also is there any way we could increase the resolution of emojis?

**Comment by hm21** [comment]
Thanks for your feature request.

I released version `4.0.6` where I added the ability that you can set a maximum and minimum scale factor in the configs to every layer type.

The resolution of the emojis depends on your device, in which quality they are available when you use the system default emojis. For the case you want to use emojis in high resolution will I recommend you to use a custom font. An example can you checkout [here](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/google_font_example.dart) where I apply `GoogleFonts.notoColorEmoji()` for high resolution.

**Comment by efalco777** [comment]
> Thanks for your feature request.
> 
> I released version `4.0.6` where I added the ability that you can set a maximum and minimum scale factor in the configs to every layer type.
> 
> The resolution of the emojis depends on your device, in which quality they are available when you use the system default emojis. For the case you want to use emojis in high resolution will I recommend you to use a custom font. An example can you checkout [here](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/google_font_example.dart) where I apply `GoogleFonts.notoColorEmoji()` for high resolution.

I overlooked that, emojis with this solution look much better. However in the example, opening emoji picker on iOS makes the app unresponsive for 3-5 seconds, could you check? If you'd like i could create a separate issue for this.

**Comment by hm21** [comment]
Does it happen in the debug mode or also in the release mode? For the case it's in release mode too, can you test if it also freezes when you just open the [emoji_picker](https://pub.dev/packages/emoji_picker_flutter) in a bottom sheet without the image editor? That will help that we know the performance impact is from the pro_image_editor package or directly from the [emoji_picker_flutter](https://pub.dev/packages/emoji_picker_flutter) package.

**Comment by efalco777** [comment]
Tested emoji picker & seems like its that package's bug.  Created an issue there, but it probably won't get addressed any time soon: https://github.com/Fintasys/emoji_picker_flutter/issues/205. Doesn't matter if it's profile/debug, at least on iOS as I've retested on physical device & simulator.

**Comment by hm21** [comment]
Okay, good idea that you create a new issue directly in the `emoji_picker_flutter` package. 

But to be honest, I think it will be a big challenge for the package owner to solve this problem. I also saw before on some platforms is a small performance impact when we scroll the emoji. The good thing is that the package owner built the project in such a way that we can edit it very detailed, which helped me to make it a bit better than the original way. 

The point is I go deep in this package and know a bit now how it works and as you can see [here](https://github.com/hm21/pro_image_editor/blob/319e105c241e29074791e873cd8dc239f99ffecf/lib/modules/emoji_editor/widgets/emoji_cell_extended.dart#L127-L131) in the end, it's a normal text widget which renders the emoji.
So, in my opinion, the problem is in the way how Flutter render it which has not a good performance. I found two videos on the web which compare flutter's graphics engine [skia](https://drive.google.com/file/d/17GxxC1NZLFZ-2QkHgMa7hQ4PNXKIAhG-/view) with the new one [impeller](https://drive.google.com/file/d/13lAIxepRE-19I_RNX7okFK6gMFb5SXqd/view) where we can also see in impeller is a small impact (if you want to see it clearly I recommend downloading the video).

So I think we have now only the following options:
- Hope that the maintainer of `emoji_picker_flutter` has some other ideas how to speed it up.
- Wait for a Flutter update where `impeller` has better performance.
- Try another emoji-font which has maybe a better performance.
- Massively reduce the amount of rendered emoji at the same time (will end up with a bad user experience)
- Convert every emoji to JPEG and render images, which might have better performance. But so many emojis will definitely have a few 100 MB or maybe GB if we want it in high resolution. Alternatively, we can convert them to SVG but this will require to use the package [flutter_svg](https://pub.dev/packages/flutter_svg).

**Comment by efalco777** [comment]
Thanks for the detailed answer. I guess I'll just keep the scale you've implemented for now in that case.
