### ISSUE TITLE
[Feature request] Before some version there was a i18n for Option inside crop & rotate option like (Free, Original) but now not available ?

### ISSUE THREAD

**Issue by amazed11** [hm21/pro_image_editor#207]
### Platforms

Android, iOS

### Description

Here, translation not available for this Free and Original.So Please add support for i18n to this specific bottomsheet options in both android and ios.

![img](https://github.com/user-attachments/assets/efd877e6-48c6-4260-baf2-436ded547ead)

### Why

Almost all the translation are available except this.

**Comment by hm21** [comment]
In the old version, translations were available for these items, as you said. However, after creating the new crop-rotate editor, I enabled users to change the aspect-ratio items themselves. Since these items are generated in the configuration as constant values, it is not possible to access the i18n file directly. Despite this, you can still change the translation by directly editing the aspect-ratio items. Below is the code demonstrating how to modify them, showing the default values as an example.

```dart
configs: ProImageEditorConfigs(
  cropRotateEditorConfigs: const CropRotateEditorConfigs(
    aspectRatios: [
      AspectRatioItem(text: 'Free', value: -1),
      AspectRatioItem(text: 'Original', value: 0.0),
      AspectRatioItem(text: '1*1', value: 1.0 / 1.0),
      AspectRatioItem(text: '4*3', value: 4.0 / 3.0),
      AspectRatioItem(text: '3*4', value: 3.0 / 4.0),
      AspectRatioItem(text: '16*9', value: 16.0 / 9.0),
      AspectRatioItem(text: '9*16', value: 9.0 / 16.0)
    ],
  ),
```
