### ISSUE TITLE
[Feature request]Requesting feature: Curve text and font name as style.

### ISSUE THREAD

**Issue by RahajulAminRaju** [hm21/pro_image_editor#229]
### Platforms

Android, iOS, Web

### Description

I want curve text system so that we can make a text curve and need to show font name as style instead of Aa.

### Why

Curve text make the editing more attractive and font name showing as style, will help us to find font quickly in the editor.

**Comment by hm21** [comment]
Hi,

It is possible to display the full font name, instead of just "Aa" with the applied font style. You can check out this [example](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/design_examples/frosted_glass_example.dart), where I also made adjustments to the design and appearance.

Regarding the feature to add curved text, I currently do not have any plans to implement it. However, if you're interested in creating a PR, I'd be happy to review it. Please note that I prefer not to rely on additional external packages, as I'm aiming to minimize dependencies within the editor.
