### ISSUE TITLE
[Bug]: Large image files dont load and crop (the app crashes)

### ISSUE THREAD

**Issue by ArkaanSayed** [hm21/pro_image_editor#240]
### Package Version

5.4.2

### Flutter Version

3.24.3

### Platforms

Android, iOS

### How to reproduce?

Use a image anywhere above 10MB size for the crop and rotate editor, the image will fail to load and the app will crash.Even if the image has been loaded interaction (zooming in and zooming out, croping etc) makes the app to crash

**Comment by hm21** [comment]
It sounds like the app crashes due to your device’s RAM being overloaded. Could you specify the exact device where this issue occurs? The editor generates the final image in the background after every interaction and holds it in RAM until the user completes their edits. This approach speeds up the process when the user presses the “Done” button.

If your users are on older or less powerful devices, you can adjust the `ImageGenerationConfigs` to disable background generation. This setting will only store the original image in RAM, reducing memory usage.

```dart
configs: ProImageEditorConfigs(
  imageGenerationConfigs: ImageGenerationConfigs(
    generateImageInBackground: false,
  ),
),
```

**Comment by ArkaanSayed** [comment]
Yes, thank you so much for replying so soon.
I was going through the code and I noticed after every interaction an image is captured..I had commented that part of the code but then the crop was not working. Adding this flag helped a lot thank you

**Comment by ArkaanSayed** [comment]
Hi, I have integrated within my application and I am only using the crop and rotate editor in my app. I tried to generateImageInBackground set this to false. But on interaction the app crashes, I am not able to zoom in or zoom out the app just crashes. I am not sure if it because of how the entire app is coded out !
The app I build is like a photo book generator, so I am dealing with multiple images in a single screen. The user can edit / crop an image and for that I am using this plugin. But for larger image sizes it crashes

**Comment by hm21** [comment]
It sounds like your RAM might be overloaded. The image editor requires the full image to be loaded without setting `cacheWidth` or `cacheHeight` to ensure that zooming and other transformations work correctly. However, if you're working with multiple images on the screen, you might try setting `cacheWidth` and `cacheHeight` individually for each image to the necessary dimensions. This approach could potentially help prevent the app from crashing.

**Comment by ArkaanSayed** [comment]
I am using cacheWidth and cacheHeight but the app still crashes. Could we resize the image inside the plugin to a certain size so that the crop tool works fine ?

**Comment by hm21** [comment]
No, that's not possible, you will need to do that before you open the image editor. Also, the editor can’t use `cacheWidth` and `cacheHeight` because zooming in will show the image at the wrong resolution.

I tested the editor with a 20MB image on native devices (Galaxy S10 and iPhone 12), and it didn’t crash. Did the app by you crash on native devices or just on emulators? And on which exact device you had this issue?
