### ISSUE TITLE
Allow Custom Widget as Icon for PaintModeBottomBarItem[Feature request] 

### ISSUE THREAD

**Issue by Pratik-1620** [hm21/pro_image_editor#257]
### Platforms

Android, iOS

### Description

I'm using this package from last 6 month and it's great!. 

The PaintModeBottomBarItem class currently only accepts IconData for its icon parameter. I would like the ability to use any Widget or SVG icons for this parameter instead of being limited to IconData. I reviewed the documentation but couldn't find an option to customize this. Is there a way to allow this customization?

Also, I reviewed the code and it's supporting only `IconData` for the image. Please refer below code snippets.

```
PaintModeBottomBarItem({
  required this.mode,
  required this.icon,  // Change from `IconData` to `Widget`
  required this.label,
});
```

**Comment by hm21** [comment]
Hi,

If you'd like to modify the entire `widget` rather than just the `iconData`, you’ll need to use `customWidgets`. This option gives you full flexibility to customize every detail to your requirements. You can refer to [this example](https://github.com/hm21/pro_image_editor/blob/ec9569ab16955144a132a224112b3f0c1ce79d0b/example/lib/pages/custom_appbar_bottombar_example.dart#L743-L806), which demonstrates how to create a custom `bottomBar`. From there, you’ll be able to modify the icon and any other elements as needed.
