### ISSUE TITLE
[Bug]: Switching the screen from portrait to landscape shifts all layers wrong

### ISSUE THREAD

**Issue by saif-ellafi** [hm21/pro_image_editor#283]
### Package Version

6.0.0

### Flutter Version

3.24.5

### Platforms

Android, iOS

### How to reproduce?

Open an image and fill it with drawings and texts in a given position, then rotate the device into landscape. You'll notice the layers are all offset in incorrect relative positions to the background image position.

| Landscape | Portrait |
|---------|---------|
| ![Screenshot 1](https://github.com/user-attachments/assets/c5b06149-63c3-4d5f-bb58-d9171787cafd) | ![Screenshot 2](https://github.com/user-attachments/assets/671dca64-3c18-48f3-b743-4de6bbcf1d90) |

**Comment by hm21** [comment]
Thank you for reporting this issue.

I noticed that you are using a custom `AppBar` and `BottomBar`. Does the issue also occur when you use the default `AppBar` and `BottomBar`, or does it happen only in this specific case?

**Comment by saif-ellafi** [comment]
Hello @hm21 ! Thanks for looking into this and your amazing work. It is the default AppBar but I added custom widgets to it, afaik. Will check again but for sure the basis is the default setup, just custom themes and a custom text editor widget.

**Comment by hm21** [comment]
Okay, if it's the default `AppBar` and you've just changed some custom widgets in it, that shouldn't be the problem. 

Currently, I think the issue is from the stickers (which might be a bit hard to fix). I just tested by me with emojis and some paintings and the reposition and scaling is correct. So if you have time, you could also try on your end if it works with the standard elements like emojis and paintings that we can be sure the problem is just from the stickers.

**Comment by saif-ellafi** [comment]
The problem I perceived as you can see in my screenshots, is with Text layers and with painting layers. I have not tried with widgets but I can check later when I get back

**Comment by saif-ellafi** [comment]
Here some more screenshots from the user who reported this

![Screenshot_2024-12-12-21-16-53-831_com discord](https://github.com/user-attachments/assets/388f344e-94d4-4de8-bcea-2afe7d82e71b)
![Screenshot_2024-12-12-21-16-58-708_com discord](https://github.com/user-attachments/assets/eda000fb-79d2-4782-b735-87fc4441746e)

**Comment by hm21** [comment]
Ah, I see! I thought you were using input text fields as stickers rather than the default text editor, cuz I remember we talked about this in the discuss-tab. Anyway, maybe the issue might be related to the `SafeArea`, which could be providing incorrect dimensions to the editor. Based on your images, it looks like the repositioning is slightly off.

Before jumping to conclusions, we should conduct further testing. Could you try using the Windows or MacOS emulator to see if the layers move/scale correctly when you slowly resize the window from one side to the other?

**Comment by saif-ellafi** [comment]
Will take a look. This implementation is the TextLayer custom widget that takes the position of the mouse cursor!

Will test with the default Text editor asap to discard that as an issue

**Comment by saif-ellafi** [comment]
Hello @hm21 ! collected some more information this morning, this week I won't be able to try different things yet but hope this helps:

1. No problems whatsoever with resizing the image editor at all, in different devices for different kind of layers. It works perfectly fine whatsoever.

2. The offset seems to be particular to switching to landscape, to notice it properly you have to try with very precise layers, like in this example:

## Portrait mode (reference)
![Simulator Screenshot - iPhone 16 Plus - 2024-12-13 at 11 26 02](https://github.com/user-attachments/assets/21bff429-09c8-4907-abd5-30977e4def76)

## Landscape mode (after change - notice eye circle is off and the hip text off too)
![Simulator Screenshot - iPhone 16 Plus - 2024-12-13 at 11 26 12](https://github.com/user-attachments/assets/6d2b3f23-e09f-43db-bcf7-c0d1455617e5)

3. Custom widget text layer or default text layer behaves the same

4. Proof that resizing window is no issue
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/e5cfc2b9-fc8f-4785-9924-b251cabd6416" />

<img width="296" alt="image" src="https://github.com/user-attachments/assets/85438400-33ef-42b8-bb21-6a4b850bb5d3" />

**Comment by hm21** [comment]
Okay, that's good to know. In both cases (resize and rotate), I use the `ScreenResizeDetector` widget to monitor changes in screen dimensions and recalculate the size and position of the layers. If the resizing functionality works correctly, the calculation process itself should also be correct.

However, I suspect that the issue lies with the `SafeArea`, which might be providing incorrect results. When you have time, could you try removing the `SafeArea` [here](https://github.com/hm21/pro_image_editor/blob/2ed797f589cc004e6b4d31b9c793dba95a4973b0/lib/widgets/screen_resize_detector.dart#L78-L81) to see if the result is better? It’s possible that we may need to apply the `SafeArea` differently, but I’m not entirely sure about this.

Currently, I’m busy with a few other projects, but if I find some time, I’ll also test whether this change resolves the issue.

**Comment by saif-ellafi** [comment]
Sure thing, will try when I can.

It's a long shot but I've been thinking, could it be the case that there is an out of sync with frame rendering? I am not familiar with how ScreenResizeDetector, but since switching to landscape is a transition with many frames in between, could it be that it will work well if we recalculate screen offsets a few frames later?

**Comment by hm21** [comment]
Technically this can make problems, but for this case I've created a class called [Debounce](https://github.com/hm21/pro_image_editor/blob/2ed797f589cc004e6b4d31b9c793dba95a4973b0/lib/utils/debounce.dart) which should prevent this problem because it only calls the update callback if the screen size hasn't changed for at least 50ms. But we may also need to change this duration, which will fix it. When you do your tests, you can change this time [here](https://github.com/hm21/pro_image_editor/blob/2ed797f589cc004e6b4d31b9c793dba95a4973b0/lib/widgets/screen_resize_detector.dart#L58). 
In my tests on a native Galaxy S10, the function was called only once after rotation. On iPhone devices, the behavior might be different, possibly calling it twice or more.

**Comment by saif-ellafi** [comment]
Hello @hm21 - tried here on the go super fast.
Your theory proves correct, the SafeArea was the culprit, with the below snippet of code, it works perfectly fine.

Are you aware of the side effects? for I could perceive none.

```dart
      Size newSize = Size(
        constraints.biggest.width,
        constraints.biggest.height,
      );
```
![Simulator Screenshot - iPhone 16 Plus - 2024-12-17 at 10 59 44](https://github.com/user-attachments/assets/e68693bd-078d-40cf-98c2-8f4c9e1c6eb4)
![Simulator Screenshot - iPhone 16 Plus - 2024-12-17 at 10 59 35](https://github.com/user-attachments/assets/fc65d32d-196c-4a77-bd8f-f103f388af3d)
![Simulator Screenshot - iPhone 16 Plus - 2024-12-17 at 10 59 21](https://github.com/user-attachments/assets/1a7d6a7f-5b18-4bfe-ae7e-29c7987d7bb2)
![Simulator Screenshot - iPhone 16 Plus - 2024-12-17 at 10 59 15](https://github.com/user-attachments/assets/94621d0b-eb5d-4d24-8bb1-d3e08593b915)

**Comment by saif-ellafi** [comment]
I noticed the `PaintEditor` does not apply the `ScreenResizeDetector` - I am trying to apply it but I couldn't figure it out yet, how to apply it correctly. While in painting editor, the rotation is not recalculating offsets.

Any ideas on where exactly to apply the ScreenResizeDetector widget in the PainEditor so it also ignores the SafeArea?

**Comment by hm21** [comment]
At the moment, the `paintEditor` does not support resizing for any layers.

It should be possible to reuse the existing function [recalculateLayerPosition](https://github.com/hm21/pro_image_editor/blob/2feb510006bc7b3dbde54faf58766c356d3db79f/lib/modules/main_editor/utils/sizes_manager.dart#L111-L156) in combination with the `ScreenResizeDetector`, similar to its implementation in the main editor.
However, this will only work for existing layers. For newly created paintings, a different calculation will be necessary because active paintings currently use the top-right corner as the zero position, rather than the center of the editor.

**Comment by saif-ellafi** [comment]
Alright, I am not sure I am capable of fixing it for the PaintEditor, but I can cover the basics for the main editor. Shall I submit a PR or live under a fork until you take care of it fully?

Thanks a lot

**Comment by saif-ellafi** [comment]
@hm21 Hey Alex,
Actually after some thought, if the issue with the PaintEditor only happens with new ongoing paintings, it isn't that terrible, as a user is typically drawing on a screen position set for that drawing, they can always correct those new layers at the new position.

Of course if a user is kind of pen-drawing, they may be often reposition their tablet one way to another and this could be somewhat problematic in the detail.

Just a thought, would be of course great if screen rotation adjusted currently active layers, but we can buy time if the first issue is already fixed for everything else.

**Comment by hm21** [comment]
Okay, I will review and then merge your PR.

Also, as a temporary solution, you could consider locking the screen orientation to either portrait or landscape mode while the user has the paint editor open. While this isn’t an ideal solution, it will help prevent unexpected results.

As example:
```dart
SystemChrome.setPreferredOrientations([
  DeviceOrientation.portraitUp,
  DeviceOrientation.portraitDown,
])
```
