### ISSUE TITLE
[Bug]: Custom Text background is crached

### ISSUE THREAD

**Issue by hoannk310** [hm21/pro_image_editor#288]
### Package Version

6.2.2

### Flutter Version

3.27.0

### Platforms

iOS

### How to reproduce?
In code example

![Simulator Screenshot - iPhone 15 - 2024-12-16 at 18 15 55](https://github.com/user-attachments/assets/c42cf6af-52c3-4248-9b1c-c1be80240272)

**Comment by hm21** [comment]
Thank you for reporting this issue.

That issue is from the [rounded_background_text](https://github.com/bdlukaa/rounded_background_text) package, which is used from the `pro_image_editor`. I would appreciate it if you could create the issue in that repository, as I also don't have enough knowledge about that package how to fix it.

**Comment by ghost** [comment]
@hm21 If I can't fix it, is there any way to set the background to be a square container instead of scaling according to the text?

**Comment by ghost** [comment]
@hm21 for example:
<img width="175" alt="Screenshot 2024-12-18 at 12 18 39 AM" src="https://github.com/user-attachments/assets/92002fc0-37f0-45d7-a2ad-1b60878fb423" />

**Comment by hm21** [comment]
This functionality is not available by default. However, you can implement a custom solution to add text inside a container as a sticker in the editor. The following [example](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/stickers_example.dart) shows how to do that.
