### ISSUE TITLE
[Bug]: `onImageEditingComplete` return empty byte's list when use web with Android or iOS devices

### ISSUE THREAD

**Issue by mahdiyarz** [hm21/pro_image_editor#36]
### Package Version

2.7.1

### Flutter Version

3.19.6

### Platforms

Web

### How to reproduce?

Hi, thank you for the great job
When I use Flutter web, `onImageEditingComplete` works fine with laptop browsers but after open Flutter web with any mobile device (Android/iOS devices) returns empty list!

**Comment by hm21** [comment]
Hi, thanks for reporting an issue. I just tested it on iPhone 10 and Samsung Galaxy 10 and everything works fine. 
Are you using a specific web browser on your mobile devices? Can you test the [example](https://hm21.github.io/pro_image_editor) and give me feedback if you see a result image after editing. Important add at least one layer like an emoji for it that the example work correctly.
For the case it work in the example, can you post the code from the ProImageEditor widget as you use it?

**Comment by mahdiyarz** [comment]
I have tasted example in my mobile browsers and works fine!
Would you please help me to find out where is the problem?

Image is picked by `image_picker` package that returns a `XFile` image. Then convert the `XFile` to `Uint8List` and use `ProImageEditor.memory` to edit image.
When use iOS app by simulator, Android app by simulator and real device and also web version by laptop (CanvasKit) everything works fine but doesn't work with mobile devices browsers, e.g. Chrome or Safari (HTML Renderer).

Also when I try to run web version by this command `flutter run -d chrome --web-renderer html` on laptop, doesn't work again as like mobile devices and `onImageEditingComplete` returns a empty list!

This is my code:

Imege is picked by `image_picker` and set image info in `selectedByteImage` value:
```Dart
XFile? imageXFile;
Uint8List? selectedByteImage;

onOpenCamera: () async {
   imageXFile = await HelperImagesFile.takeImage(
      attemptId,
   );
   if (imageXFile != null) {
      selectedByteImage = await imageXFile!.readAsBytes();
      setState(() {});
   }
},

onOpenGallery: () async {
   imageXFile = await HelperImagesFile.browseGallery(
      attemptId,
   );

   if (imageXFile != null) {
      selectedByteImage = await imageXFile!.readAsBytes();
      setState(() {});
   }
},
```

This is the `ProImageEditor.memory` function:
```Dart
onEdit: () async {
   await Navigator.push(
      context,
      MaterialPageRoute(
         builder: (context) => ProImageEditor.memory(
            selectedByteImage!,
            configs: CustomProImageEditor.imageEditor(),
            onImageEditingComplete: (byte) async {
               setState(() {
                  selectedByteImage = byte;
               });
               Navigator.pop(context);
            },
         ),
      ),
   );
},
```

When editing has been completed and pressed save button `byte` returns a empty list as I mentioned before!

**Comment by hm21** [comment]
Ah, okay that's interesting, but you're right with the `html` renderer it won't work anymore. The example only runs with the canvas renderer. The filter editor also makes problems on older android devices, that's the reason why I recommend [here](https://pub.dev/packages/pro_image_editor#web) users to always use the `canvas` renderer also for mobile devices.

Anyway, I did some testing and research and found out that the problem is the package `screenshot` that I use to create the new image. Even the package says it's made for the web, and they don't write anything about it that the html renderer not working, the issues are full of reports. I think it should be technically possible to also support the `html` renderer but it's a lot of work to do that. To be honest, I also don't think they will support the html renderer in the future. 
After I release the new crop-rotate-editor I will also write directly in the readme file that the editor only supports the canvas renderer. The problem is that the HTML renderer does not support many things like “filters”, “shadows”, “various paint operations”  that are important, but with the `canvas` renderer it's easy to do “everything” like on the other platforms.
I know the `canvas` renderer takes a little longer to start because we have to download about 1.5 MB for the canvas package from flutter, but to be honest, flutter will be slow on the web anyway and flutter is a bad choice if we need a fast startup time on the web. 
So the only solution at the moment will be for you to set the canvas renderer in your index.html file also to the default renderer until the `screenshot` package will support the html renderer.

Btw, I recommend you to use on all platforms except `web` the `ProImageEditor.file` directly without converting it to a Uint8List. I support in the editor `network`, `asset`, `memory` and `file` which will not slow down your app when you converting it first. Below I post a short example code how you can do that.


```dart
final ImagePicker picker = ImagePicker();
  final XFile? image = await picker.pickImage(source: ImageSource.gallery);

  if (image != null && context.mounted) {
    ProImageEditorConfigs configs = const ProImageEditorConfigs();
    onImageEditingComplete(Uint8List byte) async {
      selectedByteImage = byte;
    }

    onCloseEditor() async {
      Navigator.pop(context);

      if (selectedByteImage != null) {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) {
              return PreviewImgPage(imgBytes: selectedByteImage!);
            },
          ),
        );
      }
    }

    selectedByteImage = !kIsWeb ? null : await image.readAsBytes();

    if (!context.mounted) return;

    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => !kIsWeb
            ? ProImageEditor.file(
                File(image.path),
                configs: configs,
                onImageEditingComplete: onImageEditingComplete,
                onCloseEditor: onCloseEditor,
              )
            : ProImageEditor.memory(
                selectedByteImage!,
                configs: configs,
                onImageEditingComplete: onImageEditingComplete,
                onCloseEditor: onCloseEditor,
              ),
      ),
    );
```

**Comment by mahdiyarz** [comment]
Thank you for complete description. After many searches in Medium and your description, finally, I assume, canvas renderer is the best solution that I can focus on it.
