### ISSUE TITLE
Feature Request: Saving/Loading Editor State

### ISSUE THREAD

**Issue by azambuilds** [hm21/pro_image_editor#4]
**Is your feature request related to a problem? Please describe.**
It would be great to save and load editor state, e.g. state can be saved as a json file which than can be loaded. My used case would be a server generating elements like text content, etc. and then sending a pre-built state to the app which then loads it.

**Describe the solution you'd like**
serializable state, something like a json file which contains the layout of elements, as well as information about the transformations applied to the base image (although I expect this second part to be more difficult, the most important thing would be loading elements onto the picture)

**Describe alternatives you've considered**
The alternative I've considered is well...using a different editor package, but I can't find a suitable one.

**Additional context**
If I recall correctly, https://github.com/imgly/pesdk-flutter has state serialization/deserialization, but the api is outdated (I can't even build it on android)

**Checklist**
- [X] I have searched the existing issues to ensure that this feature has not already been requested or implemented.
- [X] I understand that feature requests are subject to review and may not be implemented immediately.

**Comment by hm21** [comment]
Hi Azam,

That's an interesting enhancement. To export and import, the state of the image editor should be possible. Currently, I'm already saving every layer's state in a list, so I just need to develop a method for exporting that converts it into a JSON file. However, the challenge lies in handling the following editors: `Filter`, `Crop/Rotate`, and `Sticker`. Let me explain each part in more detail.

### Filter-Editor
So, currently, when we save the filter editor, it takes a screenshot and returns it as a new Uint8List image. I want to change this so that in the main editor, the filters are rendered directly. Instead of always saving a full image in the JSON file, we'll just store a list of applied filters.

### Crop/Rotate
This will be the trickiest part. Currently, I'm using `ExtendedImage` to crop and rotate images, which directly crops the image to the new size and returns it as a Uint8List. That we can only save the state of the transformation, we'll need to build our own editor for this. I've already started working on a solution in the dev branch, which also includes animating the rotation of an image. But completing the full editor will take a lot more time. The only solution for now seems to be saving the cropped image directly in the JSON file, which will look something like this.
```json
{
    "layers": [],
    "images": []
}
```
But honestly, I'm not a fan of saving images directly in the JSON file. It'll just bloat the file, and if we're using a backend like Firestore on Firebase, we'll hit that 1 MiB document limit fast. So, I'm thinking we should add some export options. Users can choose whether to include an images array or not. This way, we can save the image list in a more efficient storage solution like cloud storage if needed.


### Sticker-Editor
So, the thing is, the user adds their widget, but the only way around it is to turn it into an image and then stash it in our JSON. I'm not sure if I can easily archive this, but I will try it, and maybe also with the option to save it in a separate image list.


So my plan is now like that:

- [x] Create export/import method for editor states.
- [x] Revise filter editor to save filter type instead of full image.
- [x] Enable export/import for stickers.
- [ ] Modify Crop/Rotate editor to save only transform states.

**Comment by azambuilds** [comment]
Thanks very much for your comment Alex,

I agree that crop/rotate would be quite difficult to implement, the best I can think of would be something like saving all edits and re-applying them when the editor is re-initializing.

I also agree that having an export, basically a "project file" would work. 

Your looks quite good to me, I look forward to seeing any progress! I'm very grateful for the work you've put into this amazing package!

**Comment by hm21** [comment]
Hey Azam,

I've just released a new version of the editor, version `2.3.0`. This update includes support for exporting and importing state history. I've run some basic tests, so while everything seems to be working fine in my tests, there might still be some bugs.

Additionally, I've updated the readme.md file with basic examples demonstrating how to import and export the state history, along with optional configurations.

### FYI:

1. **Crop-Rotate-States:** Currently, the crop-rotate state can only be exported as an image (Uint8List). However, once I've finished replacing the current crop-rotate editor with a better solution, it will be possible to export only the transform states without the full image. I've saved the images from crop-rotate and stickers at the top level of the JSON, making it easy for you to remove them from the file and upload them to any other storage if you prefer not to save the images directly in the JSON storage. Remember when you import it to add the same list to the Json file.
2. **Sticker-States:** In the custom sticker editor, all stickers will be converted to images and saved in the JSON as a list under stickers. I believe this is the best approach for handling custom user widgets.

Please let me know if you have any questions, improvements, or issues!

**Comment by azambuilds** [comment]
Awesome thanks so much! This is basically everything I needed! I'll go play around with this for a while and I'll be sure to get back if I have any suggestions for improvements or if I come across any issues!

Thanks again!
