### ISSUE TITLE
[Bug]: Delete drag target seems offset to the left on iPhone with cut out

### ISSUE THREAD

**Issue by adamkoch** [hm21/pro_image_editor#75]
### Package Version

3.0.7-dev.1

### Flutter Version

3.22.2

### Platforms

iOS

### How to reproduce?

Spotted another bug :) The delete drop target in the top left corner seems to be offset to the left on an iPhone with cutout. The actual icon is correct, just the drop target is offset.

This may help explain it better, the red box is where it seems I need to drag to in order to trigger delete (where the delete area turns red).

![Simulator Screenshot - iPhone 15 Pro - 2024-06-10 at 22 42 11](https://github.com/hm21/pro_image_editor/assets/869261/3fda1149-b637-40e9-9cd6-c18b71089fc2)

**Comment by hm21** [comment]
Okay, that's interesting because it seems like something with the `SafeArea` is failing. In the discussion [#68](68) I saw in your picture, it seems to be the same problem. Can you try two things now:

1. Wrap the `ProImageEditor` widget inside a `SafeArea`.
2. Make sure that nowhere in your code does it override the `SystemUiOverlayStyle`. The easiest way to test this is to clone the [example](https://github.com/hm21/pro_image_editor/tree/stable/example) and try it there.
3. Move in the editor the `SafeArea` [here](https://github.com/hm21/pro_image_editor/blob/49bc149cd6918ecb58fa2901d09d38de67c213be/lib/modules/main_editor/main_editor.dart#L1814) above the `ScreenResizeDetector` [here](https://github.com/hm21/pro_image_editor/blob/49bc149cd6918ecb58fa2901d09d38de67c213be/lib/modules/main_editor/main_editor.dart#L1789C16-L1789C36) and try again.

If nothing resolves this issue, I need to know the exact device model. But to be honest, if nothing fixes this, it looks like this is a problem with the flutter framework.

**Comment by adamkoch** [comment]
Thanks for the pointers. Will have a play and see what I can find with `SafeArea` and `ScreenResizeDetector`.

FWIW, I tested with pro_image_editor sample and it also has the same behaviour with the delete target. The device is iPhone 15 Pro simulator in landscape mode.

Can you point me to the code which has the delete drag target? I can have a play and see if I can work out what's wrong.

**Comment by adamkoch** [comment]
I think I found it:
https://github.com/hm21/pro_image_editor/pull/79
